export enum ENVEnum {
  NODE_ENV = 'NODE_ENV',
  DATABASE_URL = 'DATABASE_URL',

  PORT = 'PORT',
  BASE_URL = 'BASE_URL',

  JWT_SECRET = 'JWT_SECRET',
  JWT_EXPIRES_IN = 'JWT_EXPIRES_IN',
  REFRESH_TOKEN_LENGTH = 'REFRESH_TOKEN_LENGTH',
  REFRESH_TOKEN_EXPIRES_DAYS = 'REFRESH_TOKEN_EXPIRES_DAYS',

  MAIL_USER = 'MAIL_USER',
  MAIL_PASS = 'MAIL_PASS',

  REDIS_HOST = 'REDIS_HOST',
  REDIS_PORT = 'REDIS_PORT',

  TWILIO_ACCOUNT_SID = 'TWILIO_ACCOUNT_SID',
  TWILIO_AUTH_TOKEN = 'TWILIO_AUTH_TOKEN',
  TWILIO_PHONE_NUMBER = 'TWILIO_PHONE_NUMBER',

  SUPER_ADMIN_EMAIL = 'SUPER_ADMIN_EMAIL',
  SUPER_ADMIN_NAME = 'SUPER_ADMIN_NAME',
  SUPER_ADMIN_USERNAME = 'SUPER_ADMIN_USERNAME',
  SUPER_ADMIN_PHONE = 'SUPER_ADMIN_PHONE',
  SUPER_ADMIN_PASS = 'SUPER_ADMIN_PASS',

  AWS_REGION = 'AWS_REGION',
  AWS_ACCESS_KEY_ID = 'AWS_ACCESS_KEY_ID',
  AWS_SECRET_ACCESS_KEY = 'AWS_SECRET_ACCESS_KEY',
  AWS_S3_BUCKET_NAME = 'AWS_S3_BUCKET_NAME',

  CLOUDINARY_CLOUD_NAME = 'CLOUDINARY_CLOUD_NAME',
  CLOUDINARY_API_KEY = 'CLOUDINARY_API_KEY',
  CLOUDINARY_API_SECRET = 'CLOUDINARY_API_SECRET',
  FRONTEND_URL = 'FRONTEND_URL',
}
